Repository expertisesolutions/efl, pull requests merged in 2020-06, with the labels that each got.

#91 Fixing some windows includes with WIN32_LEAN_AND_MEAN
  src/generic/evas/common/timeout.c
  src/lib/ecore/ecore.c
  src/lib/ecore/ecore_exe_win32.c
  src/lib/ecore/ecore_pipe.c
  src/lib/ecore/efl_thread.c
  src/lib/ecore_con/ecore_con.c
  src/lib/ecore_con/ecore_con_local.c
  src/lib/ecore_file/ecore_file.c
  src/lib/ecore_file/ecore_file_monitor_win32.c
  src/lib/ecore_win32/ecore_win32.c
  src/lib/ecore_win32/ecore_win32_clipboard.c
  src/lib/ecore_win32/ecore_win32_cursor.c
  src/lib/ecore_win32/ecore_win32_dnd.c
  src/lib/ecore_win32/ecore_win32_dnd_data_object.h
  src/lib/ecore_win32/ecore_win32_dnd_drop_source.h
  src/lib/ecore_win32/ecore_win32_dnd_drop_target.h
  src/lib/ecore_win32/ecore_win32_dnd_enumformatetc.h
  src/lib/ecore_win32/ecore_win32_event.c
  src/lib/ecore_win32/ecore_win32_monitor.c
  src/lib/ecore_win32/ecore_win32_window.c
  src/lib/efreet/efreet_trash.c
  src/lib/eina/eina_log.c
  src/lib/eina/eina_prefix.c
  src/lib/eina/eina_sched_win32.c
  src/lib/eina/eina_thread_win32.h
  src/lib/elementary/elm_main.c
  src/lib/evas/canvas/evas_async_events.c
  src/lib/evas/common/evas_image_scalecache.c
  src/lib/evil/evil_fcntl.c
  src/lib/evil/evil_locale.c
  src/lib/evil/evil_strings.h
  src/lib/evil/evil_time.c
  src/lib/evil/evil_unistd.c
  src/lib/evil/evil_windows.h
  src/lib/evil/unposix/sys/time.h
  src/modules/ecore_evas/engines/win32/ecore_evas_win32.c
  src/modules/evas/engines/software_ddraw/Evas_Engine_Software_DDraw.h
  src/modules/evas/engines/software_ddraw/evas_engine.h
  src/modules/evas/engines/software_gdi/Evas_Engine_Software_Gdi.h
  src/modules/evas/engines/software_gdi/evas_engine.h
  src/tests/edje/edje_test_edje.c
  src/tests/evil/evil_suite.c
  src/tests/timeout.c
Labels: bug

#104 Linux Build: Make Nugget variable only on windows build
  meson.build
Labels: bug

#106 Linux Build: pipe function were not available at a linux build
  src/lib/eina/eina_debug_timer.c
  src/lib/eina/eina_pipe.h
  src/lib/eina/meson.build
  src/lib/evil/evil_unistd.h
Labels: bug

#108 Linux Build: Correct a typo
  src/lib/eina/eina_log.c
Labels: bug

#110 Linux Build: Resolve implicity declaration at `eina_inline_lock_posix.x`
  src/lib/eina/eina_inline_lock_posix.x
Labels: bug

#111 Remove unnecessary additional argument
  src/lib/eina/eina_main.c
Labels: bug

#114 Resolve wrong variable array length conversion
  src/tests/efl_check.h
Labels: bug

#122 OSX Build: Resolve typo of type Eina_ThreadId
  src/lib/eina/eina_thread_posix.h
Labels: bug

#121 Reenable Lua
  meson.build
Labels: bug

#128 Resolve eina_thread_self_id() typo
  src/lib/eina/eina_log.c
Labels: bug

#127 Initialize _eina_tracking_lock
  src/lib/eina/eina_main.c
Labels: bug

#124 Only use {Enter/Leave}CriticalSection in eina_lock_{take,release} while dealing with _eina_tracking_lock
  src/lib/eina/eina_inline_lock_win32.x
Labels: enhancement

#103 Make #89 compilation process achieve the same point of native-windows on Linux
  src/lib/ecore/meson.build
Labels: bug

#112 Linux Build: Use Eina_Lock instead of pthread_mutex_t
  src/lib/eina/eina_inline_lock_posix.x
Labels: bug

#132 Include evil only on windows build at ecore_anim.c
  src/lib/ecore/ecore_anim.c
Labels: bug

#125 OSX build: Remove double definition functions
  src/lib/eina/eina_inline_lock_posix.x
  src/lib/eina/eina_lock.c
Labels: bug

#145 Configure Travis-CI to work on expertise/efl
  .travis.yml
Labels: infra

#168 unistd imports fix
  src/bin/eet/eet_main.c
  src/bin/eolian/main.c
  src/lib/ecore/ecore.c
  src/lib/ecore/ecore_anim.c
  src/lib/ecore/ecore_main.c
  src/lib/ecore/ecore_main_timechanges.c
  src/lib/ecore/ecore_thread.c
  src/lib/ecore/ecore_throttle.c
  src/lib/ecore/ecore_time.c
  src/lib/ecore/efl_appthread.c
  src/lib/ecore/efl_loop.c
  src/lib/ecore/efl_loop_message.c
  src/lib/ecore/efl_loop_message_handler.c
  src/lib/ecore/efl_thread.c
  src/lib/ecore_input/ecore_input_joystick.c
  src/lib/eet/eet_cipher.c
  src/lib/eet/eet_lib.c
  src/tests/eet/eet_test_cache.c
  src/tests/eet/eet_test_cipher.c
  src/tests/eet/eet_test_file.c
  src/tests/eet/eet_test_identity.c
  src/tests/eet/eet_test_image.c
Labels: bug

#169 [Evil] EAPI -> EVIL_API
  src/lib/evil/evil_api.h
  src/lib/evil/evil_basename.c
  src/lib/evil/evil_basename.h
  src/lib/evil/evil_dlfcn.c
  src/lib/evil/evil_dlfcn.h
  src/lib/evil/evil_fcntl.c
  src/lib/evil/evil_fcntl.h
  src/lib/evil/evil_langinfo.c
  src/lib/evil/evil_langinfo.h
  src/lib/evil/evil_locale.c
  src/lib/evil/evil_locale.h
  src/lib/evil/evil_main.h
  src/lib/evil/evil_mman.c
  src/lib/evil/evil_mman.h
  src/lib/evil/evil_stdio.c
  src/lib/evil/evil_stdio.h
  src/lib/evil/evil_stdlib.c
  src/lib/evil/evil_stdlib.h
  src/lib/evil/evil_string.c
  src/lib/evil/evil_string.h
  src/lib/evil/evil_strings.c
  src/lib/evil/evil_strings.h
  src/lib/evil/evil_time.c
  src/lib/evil/evil_time.h
  src/lib/evil/evil_unistd.c
  src/lib/evil/evil_unistd.h
  src/lib/evil/evil_util.c
  src/lib/evil/evil_util.h
  src/lib/evil/meson.build
Labels: bug

#187 [Evil] Fixing a typo in API definition
  src/lib/evil/evil_api.h
Labels: bug

#191 Eio: Correctly use simple quotes on eio build definition
  src/lib/eio/meson.build
Labels: bug
