Repository expertisesolutions/efl, pull requests merged in 2020-09, with the labels that each got.

#409 ci: Make vcpkg cache unique for each workflow change.
  .github/workflows/windows.yml
Labels: enhancement, infra

#411 elm: Fix how elm_config was created
  src/lib/elementary/elm_config.c
Labels: bug

#417 elm: Change module names
  src/modules/elementary/access_output/meson.build
  src/modules/elementary/meson.build
  src/modules/elementary/prefs/meson.build
  src/modules/elementary/test_entry/meson.build
  src/modules/elementary/test_map/meson.build
  src/modules/elementary/web/none/meson.build
Labels: bug, enhancement

#416 elm: Fix path search for app_data
  src/lib/ecore_evas/ecore_evas_module.c
  src/lib/elementary/elm_main.c
Labels: bug, enhancement

#441 win32: Create alternative to find fontconfig from vcpkg
  src/lib/evas/meson.build
Labels: bug, enhancement

#450 eolian: Fix failures on eolian_gen tests
  src/tests/eolian/eolian_generation.c
Labels: bug
