Repository expertisesolutions/efl, pull requests merged in 2020-08, with the labels that each got.

#361 win32: Guard unistd with _MSC_VER
  src/bin/edje/edje_cc_out.c
  src/bin/ethumb_client/ethumbd.c
  src/bin/ethumb_client/ethumbd_slave.c
  src/bin/exactness/injector.c
  src/bin/exactness/player.c
  src/bin/exactness/recorder.c
  src/lib/elementary/Elementary.h
  src/lib/emotion/emotion_modules.c
  src/lib/ethumb/ethumb.c
  src/lib/ethumb_client/ethumb_client.c
  src/modules/emotion/gstreamer1/emotion_gstreamer.h
  src/tests/efreet/efreet_async_test.c
Labels: bug

#363 win32: Don't compile kde legacy and deprecated efreed
  src/lib/efreet/efreet_menu.c
  src/lib/efreet/meson.build
Labels: bug

#374 win32: Define EMODAPI_WEAK for Windows
  src/lib/elementary/elm_module_helper.h
Labels: bug

#346 build, ci: Support custom CMake modules, add vcpkg to CI
  .gitattributes
  .github/workflows/windows.yml
  configure.bat
  header_checks/meson.build
  meson.build
  meson_options.txt
  src/lib/evas/meson.build
  subprojects/check.wrap
  subprojects/freetype2.wrap
  subprojects/libjpeg.wrap
  subprojects/libpng.wrap
  subprojects/packagefiles/libpng-1.6.37-2-wrap.zip
  subprojects/zlib.wrap
Labels: enhancement, infra

#382 evil: Remove OS version check
  src/lib/evil/evil_main.c
Labels: enhancement

#378 eet: Fix 'No OPENSSL_Applink' error message.
  src/lib/eet/eet_cipher.c
Labels: bug, windows-native

#383 build: Also include libname into 'Tried: <lib list>'
  header_checks/meson.build
Labels: enhancement, windows-native

#388 edje: Fix pending_threads calculation and avoid an infinite loop
  src/bin/edje/edje_cc_out.c
Labels: bug

#390 evil: Fix fcntl for F_SETLK and F_SETLKW wrong length calculation
  src/lib/evil/evil_fcntl.c
Labels: bug

#384 Eet: Resolve eet_test_cache test case
  src/tests/eet/eet_test_cache.c
Labels: bug

#398 ecore_file: Resolve ecore_test_ecore_file_operations
  src/lib/ecore_file/ecore_file.c
  src/tests/ecore/ecore_test_ecore_file.c
Labels: bug

#402 eina: Resolve eina_file01.exe
  src/examples/eina/eina_file_01.c
Labels: bug

#401 [Eet] [Examples] Fix eet-data-cipher_decipher.exe
  src/examples/eet/eet-data-cipher_decipher.c
Labels: bug

#403 Fix: get the OS temp dir
  examples_checks.py
Labels: bug
