Repository expertisesolutions/efl, pull requests merged in 2020-07, with the labels that each got.

#200 [Ecore_con] Correctly define API
  src/lib/ecore_con/Efl_Net.h
  src/lib/ecore_con/ecore_con_eet_base_eo.c
  src/lib/ecore_con/ecore_con_eet_base_eo.h
  src/lib/ecore_con/ecore_con_eet_client_obj_eo.h
  src/lib/ecore_con/ecore_con_eet_server_obj_eo.h
  src/lib/ecore_con/ecore_con_url_curl.c
Labels: bug

#201 [Evas] Correct typo `EVAS_WEAK_API` to `EVAS_API_WEAK`
  src/lib/evas/Evas_Internal.h
  src/lib/evas/Evas_Legacy.h
  src/lib/evas/canvas/evas_box_eo.c
  src/lib/evas/canvas/evas_box_eo.h
  src/lib/evas/canvas/evas_canvas_eo.h
  src/lib/evas/canvas/evas_grid_eo.h
  src/lib/evas/canvas/evas_image_eo.h
  src/lib/evas/canvas/evas_line_eo.h
  src/lib/evas/canvas/evas_main.c
  src/lib/evas/canvas/evas_object_inform.c
  src/lib/evas/canvas/evas_object_intercept.c
  src/lib/evas/canvas/evas_table_eo.h
  src/lib/evas/canvas/evas_text_eo.h
  src/lib/evas/canvas/evas_textgrid_eo.h
  src/lib/evas/include/evas_private.h
Labels: bug

#206 [ecore_x] Correct typos at API definition
  src/lib/ecore_x/meson.build
Labels: bug

#203 Resolve typo `EDJE_WEAK_API` to `EDJE_API_WEAK`
  src/lib/edje/edje_edit_eo.h
Labels: bug

#109 [Deps] eo+eolian+efl
  header_checks/meson.build
  meson.build
  src/lib/eina/eina_types.h
  src/lib/eo/eo_ptr_indirection.c
  src/tests/eina/meson.build
  src/tests/eolian/meson.build
  src/tests/evil/meson.build
Labels: bug

#245 [evas] Bug: Remove remainging EAPI
  src/lib/evas/Evas_Internal.h
Labels: bug

#244 [ethumb] Bug: Correct typo while including ethumb api header
  src/lib/ethumb/Ethumb_Plugin.h
Labels: bug

#243 [modules] Bug: Remove remaining EWAPI
  src/modules/elementary/web/none/elm_web_none_eo.h
Labels: bug

#247 [ecore_input_evas] Correct typo at meson compile args
  src/lib/ecore_input_evas/meson.build
Labels: bug

#241 [Ecore] Fixing a dll export
  src/lib/ecore/ecore_main.c
Labels: bug

#246 Fixing undefined useconds_t
  src/lib/evas/common/evas_image_scalecache.c
  src/lib/evil/evil_unistd.c
  src/lib/evil/evil_unistd.h
Labels: bug

#249 Add LIB_API.h to files to be installed
  src/lib/ecore/meson.build
  src/lib/ecore_audio/meson.build
  src/lib/ecore_avahi/meson.build
  src/lib/ecore_buffer/meson.build
  src/lib/ecore_cocoa/meson.build
  src/lib/ecore_con/meson.build
  src/lib/ecore_drm/meson.build
  src/lib/ecore_drm2/meson.build
  src/lib/ecore_file/meson.build
  src/lib/ecore_imf/meson.build
  src/lib/ecore_input/meson.build
  src/lib/ecore_input_evas/meson.build
  src/lib/ecore_ipc/meson.build
  src/lib/ecore_win32/meson.build
  src/lib/ecore_x/meson.build
  src/lib/edje/meson.build
  src/lib/eet/meson.build
  src/lib/eeze/meson.build
  src/lib/efl/meson.build
  src/lib/efreet/meson.build
  src/lib/eio/meson.build
  src/lib/eldbus/meson.build
  src/lib/elementary/meson.build
  src/lib/elput/meson.build
  src/lib/elua/meson.build
  src/lib/embryo/meson.build
  src/lib/emile/meson.build
  src/lib/emotion/meson.build
  src/lib/eo/meson.build
  src/lib/eolian/meson.build
  src/lib/ethumb/meson.build
  src/lib/evas/meson.build
  src/lib/evil/meson.build
Labels: bug

#255 [module] Bug: Move `extern` keyword to the right of API definitions
  src/modules/ecore_evas/engines/wayland/ecore_evas_wayland_common.c
Labels: bug

#267 Bug: Add commas between public headers
  src/lib/ecore_wayland/meson.build
  src/lib/ecore_wl2/meson.build
  src/lib/ephysics/meson.build
Labels: bug

#257 Missing unistd for linux
  src/lib/eina/eina_cpu.c
Labels: bug

#147 Getting freetype2 from meson wrap
  .gitignore
  header_checks/meson.build
  src/lib/evas/meson.build
  subprojects/freetype2.wrap
  win32-deps/meson.build
Labels: enhancement

#259 Removing redefinition of PACKAGE_SRC_DIR for linux
  src/static_libs/buildsystem/meson.build
Labels: bug

#258 Removing some left EAPI in tests
  src/tests/elementary/efl_ui_test_layout.c
  src/tests/evas/evas_test_textblock.c
Labels: bug

#235 build: Disable pkgconfig operations for MSVC (Fixes #150)
  meson.build
  src/bindings/cxx/meson.build
  src/lib/efreet/meson.build
Labels: infra

#256 Disabling evil when compiling for linux
  src/tests/evil/meson.build
Labels: bug

#272 [Linux] Bug: Add lock `.x` files to eina public headers
  src/lib/eina/meson.build
Labels: bug

#277 [WIP] [Bug] An example was using EAPI instead of EAPI_MAIN as all the others
  src/examples/elementary/toolbar_cxx_example_01.cc
Labels: bug

#279 [Bug] Correct typo at efl_mono meson.build
  src/bindings/mono/efl_mono/meson.build
Labels: bug

#278 [CI] Enable Wayland and `options-enabled` builds at Travis-CI
  .travis.yml
Labels: infra

#280 [evil] Typedef pid_t from sys/types.h.
  src/lib/evil/evil_private.h
  src/lib/evil/evil_sys_types.h
Labels: enhancement

#225 extern char **_environ is already defined by ucrt.
  src/lib/ecore/efl_core_proc_env.c
  src/lib/evil/evil_stdlib.h
Labels: bug

#296 evas: correct typo while including evil_private.h
  src/modules/evas/engines/software_generic/evas_native_dmabuf.c
Labels: bug

#290 ecore: Correct unneeded underscore
  src/tests/ecore/ecore_test_ecore.c
Labels: bug

#295 evil: Define asprintf
  src/lib/evil/evil_stdio.c
  src/lib/evil/evil_stdio.h
  src/lib/evil/evil_vasprintf.h
Labels: enhancement

#310 Define S_ISREG and guard ole2.h
  src/lib/ecore_win32/ecore_win32_dnd_enumformatetc.cpp
  src/lib/evas/include/evas_common_private.h
  src/lib/evil/evil_stat.h
Labels: bug, enhancement

#313 Rename shutdown as proxy_helper_shutdown
  src/bin/ecore_con/efl_net_proxy_helper.c
Labels: bug

#320 build: Properly handle --verbose arg
  configure.bat
Labels: enhancement, infra

#315 build: Check VS edition instead of assuming Professional
  build.bat
  configure.bat
  ensure-vcvars64.bat
Labels: enhancement, infra

#312 evil: Define sleep
  header_checks/meson.build
  src/lib/evil/evil_private.h
  src/lib/evil/evil_unistd.c
  src/lib/evil/evil_unistd.h
Labels: enhancement

#321 build: Add flag for custom builddir for configure.bat
  configure.bat
Labels: enhancement, infra

#324 build: Use installed openssl when available
  configure.bat
Labels: enhancement, infra

#328 build: Fix usage of EnableDelayedExpansion
  configure.bat
  ensure-vcvars64.bat
Labels: bug, enhancement, infra

#331 [win32] [examples] Adding guards to headers for windows compatibility
  src/examples/ecore/ecore_audio_custom.c
  src/examples/ecore/ecore_audio_playback.c
  src/examples/ecore/ecore_audio_to_ogg.c
  src/examples/ecore/ecore_con_server_http_example.c
  src/examples/ecore/ecore_con_url_download_example.c
  src/examples/ecore/ecore_evas_basics_example.c
  src/examples/ecore/ecore_evas_ews_example.c
  src/examples/ecore/ecore_evas_extn_plug_example.c
  src/examples/ecore/ecore_evas_extn_socket_example.c
  src/examples/ecore/ecore_event_example_02.c
  src/examples/ecore/ecore_exe_example.c
  src/examples/ecore/ecore_exe_example_child.c
  src/examples/ecore/ecore_fd_handler_example.c
  src/examples/ecore/ecore_idler_example.c
  src/examples/ecore/ecore_job_example.c
  src/examples/ecore/ecore_pipe_simple_example.c
  src/examples/ecore/ecore_poller_example.c
  src/examples/ecore/ecore_thread_example.c
  src/examples/ecore/ecore_time_functions_example.c
  src/examples/ecore/ecore_timer_example.c
  src/examples/eet/eet-data-cipher_decipher.c
  src/examples/eet/eet-data-file_descriptor_01.c
  src/examples/eet/eet-data-file_descriptor_02.c
  src/examples/eet/eet-data-nested.c
  src/examples/eet/eet-data-simple.c
  src/examples/eina/eina_value_03.c
  src/examples/emotion/emotion_generic_example.c
Labels: bug

#291 [wrap] Fixing jpeg
  meson.build
  native-file-windows.txt
  src/lib/emile/emile_image.c
  win32-deps/packages.config
Labels: bug

#322 build: Adds -h,--help to configure.bat
  configure.bat
Labels: enhancement, infra

#340 elm: Remove declaration from the wrong library
  src/lib/elementary/Efl_Ui.h
  src/lib/elementary/elm_main.c
  src/tests/elementary/suite_helpers.c
Labels: bug

#339 eina: Check if thread is null before accessing its values on eina_thread_cancel
  src/lib/eina/eina_thread_win32.c
Labels: bug

#341 evil: Implement evil_localtime_r using localtime
  header_checks/meson.build
  src/lib/evil/evil_time.c
  src/lib/evil/evil_time.h
Labels: enhancement

#338 evil: Rework sys/stat.h port and add file system options definitions
  src/lib/evil/evil_private.h
  src/lib/evil/evil_stat.h
  src/lib/evil/evil_sys_stat.h
Labels: enhancement

#352 ci: Minimize logs noise.
  .github/workflows/windows.yml
Labels: enhancement, infra

#351 clang: Fix enumeration signed overflow
  src/lib/edje/Edje_Common.h
Labels: bug

#292 [wrap] lua
  configure.bat
  meson.build
  native-file-windows.txt
  src/bindings/meson.build
  src/tests/elua/meson.build
  subprojects/lua.wrap
Labels: bug

#323 [Evil] Reimplementing basename
  src/lib/evil/evil_basename.c
  src/lib/evil/evil_basename.h
  src/lib/evil/evil_libgen.c
  src/lib/evil/evil_libgen.h
  src/lib/evil/evil_private.h
  src/lib/evil/meson.build
  src/tests/evil/evil_test_libgen.c
Labels: enhancement

#356 build: disable elua by default, plus nicer detection
  .ci/ci-configure.sh
  meson_options.txt
  src/bindings/meson.build
  src/lib/elua/meson.build
  src/scripts/meson.build
Labels: bug

#355 win32: Fix signed overflow with bitsets and enumerations
  src/lib/evas/canvas/evas_object_textblock.c
Labels: bug

#359 win32: Fix IF_S* macros
  src/bin/elementary/run.c
  src/lib/ecore/ecore_glib.c
  src/lib/efreet/efreet_mime.c
  src/lib/eina/eina_file.c
  src/lib/eio/efl_io_model.c
  src/lib/evil/evil_sys_stat.h
Labels: bug

#360 fix: Missing # before 'define'
  src/lib/ephysics/ephysics_api.h
Labels: bug
