Repository expertisesolutions/efl, pull requests merged in 2020-04, with the labels that each got.

#23 windows: Pass flags to build.bat straight-forwardly
  build.bat
Labels: infra, windows-native

#24 Windows:sys/time.h: Remove linking error at localtime_s
  src/lib/evil/unposix/sys/time.h
Labels: bug, windows-native

#32 windows: Enable implicit-function-declaration error.
  meson.build
Labels: infra, ready-to-merge, windows-native

#45 Add wrap for getopt
  .gitignore
  header_checks/meson.build
  src/lib/evil/unposix/getopt.h
  src/lib/evil/unposix/meson.build
  src/lib/evil/unposix/unistd.h
  subprojects/getopt.wrap
Labels: infra, windows-native

#34 Windows:eina: Add Thread synchronization
  src/lib/eina/eina_debug_bt.c
  src/lib/eina/eina_inline_lock_barrier.x
  src/lib/eina/eina_inline_lock_posix.x
  src/lib/eina/eina_inline_lock_win32.x
  src/lib/eina/eina_lock.c
  src/lib/eina/eina_lock.h
  src/lib/eina/eina_main.c
  src/lib/eina/meson.build
  src/lib/evil/unposix/meson.build
  src/lib/evil/unposix/pthread.h
  src/lib/evil/unposix/semaphore.h
Labels: enhancement, remove-dependency, windows-native

#50 Bug: Remove warnings introduced by last merge
  src/lib/eina/eina_debug.c
  src/lib/eina/eina_debug_timer.c
  src/lib/eina/eina_inline_thread_posix.x
Labels: bug
