Repository expertisesolutions/efl, pull requests merged in 2020-05, with the labels that each got.

#67 Evil: Fixing conversion from size_t to high-low dwords for _WIN64.
  src/lib/evil/evil_mman.c
Labels: bug

#71 Eina: Missing brackets at eina_vpath()
  src/lib/eina/eina_vpath.c
Labels: bug

#74 Actions: fix meson path
  .github/workflows/windows.yml
Labels: enhancement

#75 Eina: missing semicolon
  src/lib/eina/eina_inline_lock_win32.x
Labels: bug

#84 build: Use check subproject as fallback
  header_checks/meson.build
Labels: bug, windows-native
